easy_admin:
    entities:
        Exemple:
            label: "Entité exemple"
            class: AppBundle\Entity\Exemple
            list:
#                actions:
#                     - { name: 'show', icon: 'search' }
                fields:
                    - { property: 'image', template: ':admin/_fields:field_image.html.twig', type: 'image', base_path: '%app.exemple.images%' }
                    - { property: 'media', template: ':admin/_fields:field_media.html.twig', type_options: {conf: 'default'} }
                    - { property: 'contract', template: 'admin/_fields/field_contract.html.twig', base_path: '%app.exemple.contracts%' }
            form:
                  fields:
                        - { property: 'imageFile', type: 'file' }
                        - { property: 'contractFile', type: 'vich_file' }
                        - { property: 'media', type: 'Artgris\Bundle\MediaBundle\Form\Type\MediaType', type_options: {conf: 'default'}  }
                        - { property: 'date', type: 'date', type_options: {widget: 'single_text', html5: false, attr: {class: 'datepicker'}, format: 'dd/MM/yyyy', required: false} }
                        - { property: 'translations', label: 'Traductions', type: 'A2lix\TranslationFormBundle\Form\Type\TranslationsType', type_options: {fields: {title: {label: 'Titre'}, content: {label: 'Contenu', attr: {class: 'tinymce'}} }} }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.exemple.images%' }
                    - { property: 'contract', template: 'admin/_fields/field_contract.html.twig', base_path: '%app.exemple.contracts%' }