easy_admin:
    entities:
        Product:
            class: AppBundle\Entity\Product
            # ...
            form:
                fields:
                      - { property: 'imageFile', type: 'file' }
            list:
                actions:
                     - { name: 'show', icon: 'search' }
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
            # ...
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }