easy_admin:
    formats:
        date: 'd/m/Y'
        datetime: 'd/m/Y H:i:s'
#    show:
#        max_results: 5
    site_name: 'Admin'
    design:
        color_scheme: 'dark'
        brand_color: '#000000'