easy_admin:
    design:
        menu:
          - label: 'menu.dashboard'
            route: 'admin_dashboard'
            icon: 'dashboard'
            default: true
          - label: 'menu.user'
            icon: 'users'
            entity: 'User'
            icon: 'shield'
          - label: 'menu.settings'
            icon: 'wrench'
            children:
                - label: 'menu.cc'
                  route: 'admin_tools_cc'
                  icon: 'eraser'
                - label: 'menu.dsv'
                  route: 'admin_tools_checkdatabase'
                  icon: 'database'
                - label: 'menu.translate'
                  route: 'jms_translation_index'
                  icon: 'flag'