# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.subscriber.easy_admin:
        class: AppBundle\EventListener\EasyAdminSubscriber
        arguments: ['@session']
        tags:
            - { name: kernel.event_subscriber }